// config.js
import dotenv from 'dotenv';
dotenv.config();

const config = {
  OPENMRS_SOURCE_CONTEXT_PATH: process.env.OPENMRS_SOURCE_CONTEXT_PATH,
  OPENMRS_SOURCE_USERNAME: process.env.OPENMRS_SOURCE_USERNAME,
  OPENMRS_SOURCE_PASSWORD: process.env.OPENMRS_SOURCE_PASSWORD,
  OPENMRS_TARGET_CONTEXT_PATH: process.env.OPENMRS_TARGET_CONTEXT_PATH,
  OPENMRS_TARGET_USERNAME: process.env.OPENMRS_TARGET_USERNAME,
  OPENMRS_TARGET_PASSWORD: process.env.OPENMRS_TARGET_PASSWORD,
  TARGET_DIR: process.env.TARGET_DIR,
  EXPORT_PATIENT_LIST_FILE: process.env.EXPORT_PATIENT_LIST_FILE,
  EXPORT_USER_LIST_FILE: process.env.EXPORT_USER_LIST_FILE,
  EXPORT_PROVIDER_LIST_FILE: process.env.EXPORT_PROVIDER_LIST_FILE,
  EXPORT_USER_MAPPINGS_FILE: process.env.EXPORT_USER_MAPPINGS_FILE,
  EXPORT_PROVIDER_MAPPINGS_FILE: process.env.EXPORT_PROVIDER_MAPPINGS_FILE,
}

export default config;