// config.js
import dotenv from 'dotenv';
import process from 'process';
dotenv.config();

const config = {
  OPENMRS_SOURCE_CONTEXT_PATH: process.env.OPENMRS_SOURCE_CONTEXT_PATH,
  OPENMRS_SOURCE_USERNAME: process.env.OPENMRS_SOURCE_USERNAME,
  OPENMRS_SOURCE_PASSWORD: process.env.OPENMRS_SOURCE_PASSWORD,
  OPENMRS_TARGET_CONTEXT_PATH: process.env.OPENMRS_TARGET_CONTEXT_PATH,
  OPENMRS_TARGET_USERNAME: process.env.OPENMRS_TARGET_USERNAME,
  OPENMRS_TARGET_PASSWORD: process.env.OPENMRS_TARGET_PASSWORD,
  TARGET_DIR: process.env.TARGET_DIR,
  EXPORT_PATIENT_LIST_FILE: process.env.EXPORT_PATIENT_LIST_FILE,
  EXPORT_PERSON_LIST_FILE: process.env.EXPORT_PERSON_LIST_FILE,
  ZL_EMR_IDENTIFIERS_FILE: process.env.ZL_EMR_IDENTIFIERS_FILE,
  EXPORT_USER_LIST_FILE: process.env.EXPORT_USER_LIST_FILE,
  EXPORT_PROVIDER_LIST_FILE: process.env.EXPORT_PROVIDER_LIST_FILE,
  EXPORT_RELATIONSHIP_LIST_FILE: process.env.EXPORT_RELATIONSHIP_LIST_FILE,
  EXPORT_USER_MAPPINGS_FILE: process.env.EXPORT_USER_MAPPINGS_FILE,
  EXPORT_USER_ROLE_MAPPINGS_FILE: process.env.EXPORT_USER_ROLE_MAPPINGS_FILE,
  EXPORT_PATIENT_IDENTIFIERS_MAPPINGS_FILE: process.env.EXPORT_PATIENT_IDENTIFIERS_MAPPINGS_FILE,
  EXPORT_PROVIDER_MAPPINGS_FILE: process.env.EXPORT_PROVIDER_MAPPINGS_FILE,
  EXPORT_PROGRAM_WORKFLOW_STATE_MAPPINGS_FILE: process.env.EXPORT_PROGRAM_WORKFLOW_STATE_MAPPINGS_FILE,
  IMPORT_PATIENTS_BATCH_SIZE: process.env.IMPORT_PATIENTS_BATCH_SIZE,
  IMPORT_PERSONS_BATCH_SIZE: process.env.IMPORT_PERSONS_BATCH_SIZE,
  ORDER_NUMBER_PREFIX: process.env.ORDER_NUMBER_PREFIX,
  CONVERT_HAITI_2016_DATES_DURING_VERIFICATION: process.env.CONVERT_HAITI_2016_DATES_DURING_VERIFICATION,
  REDCAP_EXPORT_FILE: process.env.REDCAP_EXPORT_FILE,
  REDCAP_ADDRESSES_MAPPING_FILE: process.env.REDCAP_ADDRESSES_MAPPING_FILE,
  REDCAP_RECORDS_WITH_NO_DOB_DIR: process.env.REDCAP_RECORDS_WITH_NO_DOB_DIR,
}

export default config;